site_name: AI Engineering Handbook

theme:
  name: material

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/math.js